version: "3.9"

services:
  # -------------------------
  # ZOOKEEPER
  # -------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # -------------------------
  # KAFKA
  # -------------------------
  kafka:
    image: confluentinc/cp-kafka:7.9.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  # -------------------------
  # PATIENT DATABASE
  # -------------------------
  patient-db:
    image: postgres:latest
    container_name: patient-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patient
    ports:
      - "5433:5432"
    volumes:
      - patient-data:/var/lib/postgresql/data
      - ./sql/patient.sql:/docker-entrypoint-initdb.d/patient.sql

  # -------------------------
  # BILLING DATABASE
  # -------------------------
  billing-db:
    image: postgres:latest
    container_name: billing-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: billing
    ports:
      - "5434:5432"
    volumes:
      - billing-data:/var/lib/postgresql/data
      - ./sql/billing.sql:/docker-entrypoint-initdb.d/billing.sql

  # -------------------------
  # AUTH DATABASE
  # -------------------------
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    ports:
      - "5435:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
      - ./sql/auth.sql:/docker-entrypoint-initdb.d/auth.sql

  # -------------------------
  # PATIENT SERVICE
  # -------------------------
  patient-service:
    build: ./patientService
    container_name: patient-service
    depends_on:
      - patient-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-db:5432/patient
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"

  # -------------------------
  # BILLING SERVICE
  # -------------------------
  billing-service:
    build: ./billingservice
    container_name: billing-service
    depends_on:
      - billing-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://billing-db:5432/billing
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8090:8080"

  # -------------------------
  # AUTH SERVICE
  # -------------------------
  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - auth-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8091:8080"

volumes:
  patient-data:
  billing-data:
  auth-data:

networks:
  default:
    name: hm_default
